# Generated by Django 4.2.27 on 2026-01-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_complete',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='order_time',
        ),
    ]
