# Generated by Django 4.2.27 on 2026-02-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_orders', '0002_rename_is_complete_order_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
