# Generated by Django 4.2.27 on 2026-02-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_orders', '0003_alter_order_is_completed_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
